# -*- mode: makefile-gmake -*-

MINIFAD_DIR = ./minifad
MINIFAD_INCLUDE = -I$(MINIFAD_DIR)
AD_INCLUDE = -DMINIFAD $(MINIFAD_INCLUDE)

.PHONY: bootstrap
bootstrap: $(MINIFAD_DIR)/minifad.hpp

MINIFAD_URL = https://bitbucket.org/dalcinl/minifad/raw/master/minifad.hpp
$(MINIFAD_DIR)/minifad.hpp: $(MINIFAD_DIR)
	@curl -s $(MINIFAD_URL) > $@
$(MINIFAD_DIR):
	@mkdir $@
