CFLAGS   =
FFLAGS   =
SOURCEH  = petiga.h petigaprobe.h petscts2.h
SOURCEC  =
SOURCEF  =
OBJSC    =
OBJSF    =
LIBBASE  = libpetiga
DIRS     = #finclude private
LOCDIR   = include/
MANSEC   = IGA

include ${PETIGA_DIR}/conf/petigavariables
include ${PETIGA_DIR}/conf/petigarules
include ${PETIGA_DIR}/conf/petigatest
