CFLAGS   =
FFLAGS   =
SOURCEH  = petiga.h petigaprobe.h petscts1.h petscts2.h
SOURCEC  =
SOURCEF  =
OBJSC    =
OBJSF    =
LIBBASE  = libpetiga
DIRS     = #finclude private
LOCDIR   = include/
MANSEC   = IGA

include $(PETIGA_DIR)/lib/petiga/make/variables
include $(PETIGA_DIR)/lib/petiga/make/rules
include $(PETIGA_DIR)/lib/petiga/make/test
