CFLAGS   =
FFLAGS   =
SOURCEH  = petiga.h
SOURCEC  =
SOURCEF  =
OBJSC    =
OBJSF    =
LIBBASE  = libpetiga
DIRS     = #finclude private
LOCDIR   = include/
MANSEC   = IGA

include $(PETIGA_DIR)/lib/petiga/conf/variables
include $(PETIGA_DIR)/lib/petiga/conf/rules
include $(PETIGA_DIR)/lib/petiga/conf/test
